# This is a basic workflow to help you get started with Actions

name: CI
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remove File
      # You may pin to the exact commit or the version.
      # uses: JesseTG/rm@94440f309afcc4c37e6bf63eb0feca9e94dee5a3
      uses: JesseTG/rm@v1.0.0
      with:
        # The file path to remove
        path: /docs/_data/gmdmar-facets-daily/gmdmar-facets-.json
